// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA70MvUaqXQWYnc6-inXGsQzHeNF7svrcA',
    appId: '1:100680290556:web:f1d4d23c8618404c614779',
    messagingSenderId: '100680290556',
    projectId: 'cafeapp-6964b',
    authDomain: 'cafeapp-6964b.firebaseapp.com',
    storageBucket: 'cafeapp-6964b.appspot.com',
    measurementId: 'G-H5HQ281EMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0L9yAuE8EYt9YJ4xLjCiplIxK9mzUikw',
    appId: '1:100680290556:android:130037803bdf30a3614779',
    messagingSenderId: '100680290556',
    projectId: 'cafeapp-6964b',
    storageBucket: 'cafeapp-6964b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0QObb_DopYHumK5C5Q9u_cghs_VwPLxM',
    appId: '1:100680290556:ios:a652bca5c0dab40a614779',
    messagingSenderId: '100680290556',
    projectId: 'cafeapp-6964b',
    storageBucket: 'cafeapp-6964b.appspot.com',
    iosClientId: '100680290556-gvf1rs876oekm8grldm9krc73spjjv2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0QObb_DopYHumK5C5Q9u_cghs_VwPLxM',
    appId: '1:100680290556:ios:a652bca5c0dab40a614779',
    messagingSenderId: '100680290556',
    projectId: 'cafeapp-6964b',
    storageBucket: 'cafeapp-6964b.appspot.com',
    iosClientId: '100680290556-gvf1rs876oekm8grldm9krc73spjjv2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeApp',
  );
}
